[build]
  publish = "src"        # Directory to deploy (relative to root)
  command = "" # Build command (what Netlify will run)
  functions = "netlify/functions" # (Optional) If you're using Netlify functions

# (Optional) Define a Node.js version
[build.environment]
  NODE_VERSION = "16"
